# Generated by Django 5.2.1 on 2025-05-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Bad')])),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('light', models.IntegerField()),
                ('solidMoisture', models.IntegerField()),
                ('smoke', models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Bad')])),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
