# Generated by Django 5.2.1 on 2025-05-31 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_land', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('read_and_write', 'read_and_write'), ('read_only', 'read_only')])),
                ('greenland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.greenland')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('good', 'good'), ('normal', 'normal'), ('bad', 'bad')])),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('light', models.IntegerField()),
                ('solidMoisture', models.IntegerField()),
                ('smoke', models.CharField(choices=[('good', 'good'), ('normal', 'normal'), ('bad', 'bad')])),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('greenland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='Home.greenland')),
            ],
        ),
    ]
