# Generated by Django 5.2.1 on 2025-06-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
