# Generated by Django 5.2.1 on 2025-05-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_setrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setrole',
            name='role',
            field=models.IntegerField(choices=[(1, 'Read And Write'), (2, 'Read Only')]),
        ),
    ]
