# Generated by Django 5.2.1 on 2025-05-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_setrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='greenland',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='Home.greenland'),
        ),
    ]
