# Generated by Django 5.2.1 on 2025-05-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_zone_greenland'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='greenland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='Home.greenland'),
        ),
    ]
