# Generated by Django 5.2.1 on 2025-05-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_zone_greenland'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setrole',
            name='role',
            field=models.CharField(choices=[('read_and_write', 'read_and_write'), ('read_only', 'read_only')]),
        ),
        migrations.AlterField(
            model_name='zone',
            name='smoke',
            field=models.IntegerField(choices=[('good', 'good'), ('normal', 'normal'), ('bad', 'bad')]),
        ),
        migrations.AlterField(
            model_name='zone',
            name='status',
            field=models.CharField(choices=[('good', 'good'), ('normal', 'normal'), ('bad', 'bad')]),
        ),
    ]
