services:

  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3

    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    depends_on:
      - db
      - redis

    env_file:
      - .env

  
  db:
    container_name: postgres_db
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"


  redis:
    container_name: backend_redis
    image: redis
    ports:
      - "6379:6379"



volumes:
  postgres_data: