services:

  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    
    volumes:
      - .:/app
    
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    depends_on:
      - db
      - redis

    env_file:
      - .env

  
  db:
    container_name: postgres_db
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"


  redis:
    container_name: backend_redis
    image: redis
    ports:
      - "6379:6379"

  celery:
    container_name: backend_celery
    build: .
    command: ["celery", "-A", "GreenLandBack.celery_app", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend


  celery_beat:
    container_name: backend_celery_beat
    build: .
    command: ["celery", "-A", "GreenLandBack.celery_app", "beat", "--loglevel=info", "--schedule=/app/celerybeat_data/celerybeat-schedule"]
    volumes:
      - .:/app
      - celerybeat_data:/app/celerybeat_data
    depends_on:
      - redis
      - backend


volumes:
  postgres_data:
  celerybeat_data: